buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10'
        classpath "io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE"
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.4.1'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

apply plugin: "io.spring.dependency-management"

task clean(type: Delete) {
    delete rootProject.buildDir
}